services:
  mariadb:
    image: mariadb:latest
    container_name: mariadb_mackmusic
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: music_recommender
      MYSQL_USER: user
      MYSQL_PASSWORD: Senha123
    ports:
      - "3306:3306"